version: '3.5'
services:
  database:
    image: postgres:9.6
    restart: always
    environment:
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: "database"
      POSTGRES_USER: dev
    ports:
      - 5432:5432